// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgInfo.proto

package demo.domain;

public interface MsgBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MsgBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string channelId = 1;</code>
   */
  String getChannelId();
  /**
   * <code>string channelId = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <code>string msgInfo = 2;</code>
   */
  String getMsgInfo();
  /**
   * <code>string msgInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgInfoBytes();
}
